### ISSUE TITLE
Subsume other libs into this one?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Wire_Pads.pretty#5]
I see a few libs with only a few footprints which seem related. Perhaps they can be combined?

https://github.com/KiCad/Measurement_Points.pretty has similar footprints, many being just plated holes. The Keystone parts would fit nicely as well.

https://github.com/KiCad/Wire_Connections_Bridges.pretty might also be able to be merged here.

If so, though, a name change might be in order (best done for v5, I assume). Perhaps rename this lib to `Wires_Pads_Testpoints`? Especially based on the discussion at https://github.com/KiCad/Wire_Pads.pretty/pull/3, let's think about all of these footprints and they're both grouped and used.

@SchrodingersGat @jkriege2 @poeschlr @hackscribble @Shackmeister

**Comment by SchrodingersGat** [comment]
I'd be happy to see these merged, and named on such a way to be obviously separate from mechanical mounting holes and lugs.

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr @hackscribble @Shackmeister 
Great! Does anyone have a good suggestions for a name? I proposed one above but probably there's something better.

**Comment by SchrodingersGat** [comment]
All the test points should be moved to Connectors_TestPoints library (which is now live). 

Other suggestions:

* Connectors_Jumpers
* Connectors_Wire

**Comment by evanshultz** [comment]
Is this good to go for the new footprint library folder? I'm not sure of the structure there. and https://github.com/KiCad/kicad-footprints/blob/master/TODO.md doesn't like the two libs above. Is this merging of libs assumed to happen in the new repo?

**Comment by SchrodingersGat** [comment]
I think that these three libs should be merged into:

* Conn_Wire
* TestPoint

**Comment by poeschlr** [comment]
Should TestPoint also start with Conn_?
Would allow the footprint filter for the Conn symbol to list them. (Or is there a special symbol for test points?)

**Comment by SchrodingersGat** [comment]
I think test points are separate, there are unique symbols for these
